import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1781267711129 implements MigrationInterface {
    name = 'InitialSchema1781267711129'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('admin', 'user')`);
        await queryRunner.query(`CREATE TYPE "public"."users_status_enum" AS ENUM('active', 'inactive', 'banned')`);
        await queryRunner.query(`CREATE TYPE "public"."payments_status_enum" AS ENUM('checkout_created', 'pending', 'succeeded', 'failed', 'canceled', 'refunded', 'partially_refunded')`);
        await queryRunner.query(`CREATE TYPE "public"."notifications_type_enum" AS ENUM('ORDER_UPDATED', 'PAYMENT_SUCCESS', 'PAYMENT_FAILED', 'SYSTEM', 'BROADCAST')`);
        await queryRunner.query(`CREATE TYPE "public"."user_list_items_media_type_enum" AS ENUM('movie', 'tv')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" SERIAL NOT NULL, "email" character varying NOT NULL, "password" character varying, "name" character varying, "avatar" character varying, "role" "public"."users_role_enum" NOT NULL DEFAULT 'user', "status" "public"."users_status_enum" NOT NULL DEFAULT 'active', "googleId" character varying, "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "isEmailVerified" boolean NOT NULL DEFAULT false, "emailVerificationToken" character varying, "emailVerificationTokenExpiry" TIMESTAMP, "passwordResetToken" character varying, "passwordResetTokenExpiry" TIMESTAMP, "stripe_customer_id" character varying, "is_premium" boolean NOT NULL DEFAULT false, CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "UQ_51b8b26ac168fbe7d6f5653e6cf" UNIQUE ("name"), CONSTRAINT "UQ_f382af58ab36057334fb262efd5" UNIQUE ("googleId"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "black_list_tokens" ("id" SERIAL NOT NULL, "token" character varying NOT NULL, "userId" character varying NOT NULL, "expiresAt" TIMESTAMP NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_a136c27667742b133d262dd411f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8eb1cabd6b6e30a13c1dc85326" ON "black_list_tokens" ("token") `);
        await queryRunner.query(`CREATE INDEX "IDX_e36371b9a0eaf48419f30da4a1" ON "black_list_tokens" ("expiresAt") `);
        await queryRunner.query(`CREATE TABLE "contact_messages" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "full_name" character varying(100) NOT NULL, "email" character varying(255) NOT NULL, "subject" character varying(200) NOT NULL, "message" text NOT NULL, "is_read" boolean NOT NULL DEFAULT false, "replied_at" TIMESTAMP, "ip_address" character varying(45), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_b74f96eb2edd977ccfba6533293" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_contact_messages_created_at" ON "contact_messages" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "idx_contact_messages_is_read" ON "contact_messages" ("is_read") `);
        await queryRunner.query(`CREATE TABLE "notifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "type" "public"."notifications_type_enum" NOT NULL DEFAULT 'SYSTEM', "title" character varying(255) NOT NULL, "message" text NOT NULL, "data" jsonb, "is_read" boolean NOT NULL DEFAULT false, "read_at" TIMESTAMP, "is_deleted" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_77ee7b06d6f802000c0846f3a5" ON "notifications" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_aef1c7aef3725068e5540f8f00" ON "notifications" ("type") `);
        await queryRunner.query(`CREATE INDEX "IDX_f12148ce379462ebbb4d06cc13" ON "notifications" ("is_read") `);
        await queryRunner.query(`CREATE INDEX "IDX_9a8a82462cab47c73d25f49261" ON "notifications" ("user_id") `);
        await queryRunner.query(`CREATE TABLE "notification_preferences" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "order_notifications" boolean NOT NULL DEFAULT true, "payment_notifications" boolean NOT NULL DEFAULT true, "system_notifications" boolean NOT NULL DEFAULT true, "email_enabled" boolean NOT NULL DEFAULT true, "push_enabled" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_64c90edc7310c6be7c10c96f675" UNIQUE ("user_id"), CONSTRAINT "PK_e94e2b543f2f218ee68e4f4fad2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_64c90edc7310c6be7c10c96f67" ON "notification_preferences" ("user_id") `);
        await queryRunner.query(`CREATE TABLE "customers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" integer NOT NULL, "stripe_customer_id" character varying(255) NOT NULL, "email" character varying(255) NOT NULL, "name" character varying(255), "metadata" jsonb NOT NULL DEFAULT '{}'::jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_133ec679a801fab5e070f73d3ea" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_be246a1643960ed2529d08b8b8" ON "customers" ("stripe_customer_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_11d81cd7be87b6f8865b0cf766" ON "customers" ("user_id") `);
        await queryRunner.query(`CREATE TYPE "public"."plans_status_enum" AS ENUM('draft', 'active', 'archived')`);
        await queryRunner.query(`CREATE TABLE "plans" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "code" character varying(100) NOT NULL, "name" character varying(255) NOT NULL, "description" text, "status" "public"."plans_status_enum" NOT NULL DEFAULT 'draft', "features" jsonb NOT NULL DEFAULT '[]'::jsonb, "display_order" integer NOT NULL DEFAULT '0', "icon" character varying(255), "highlight" boolean NOT NULL DEFAULT false, "metadata" jsonb NOT NULL DEFAULT '{}'::jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_95f7ef3fc4c31a3545b4d825dd4" UNIQUE ("code"), CONSTRAINT "PK_3720521a81c7c24fe9b7202ba61" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a82db0f05657dd1382a58bc9d9" ON "plans" ("display_order") `);
        await queryRunner.query(`CREATE INDEX "IDX_9f48ef3635529b001d3b06cce0" ON "plans" ("status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_95f7ef3fc4c31a3545b4d825dd" ON "plans" ("code") `);
        await queryRunner.query(`CREATE TYPE "public"."prices_type_enum" AS ENUM('one_time', 'recurring')`);
        await queryRunner.query(`CREATE TYPE "public"."prices_interval_enum" AS ENUM('day', 'week', 'month', 'year')`);
        await queryRunner.query(`CREATE TABLE "prices" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "plan_id" uuid NOT NULL, "stripe_price_id" character varying(255) NOT NULL, "stripe_product_id" character varying(255), "currency" character varying(3) NOT NULL, "unit_amount" integer NOT NULL, "type" "public"."prices_type_enum" NOT NULL, "interval" "public"."prices_interval_enum", "trial_period_days" integer, "active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_2e40b9e4e631a53cd514d82ccd2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8f45cde063ad75609a556c071b" ON "prices" ("active") `);
        await queryRunner.query(`CREATE INDEX "IDX_91c9f1060b42b172d0883e13f4" ON "prices" ("plan_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_f6fda7cdd493f9803d5173bb3e" ON "prices" ("stripe_price_id") `);
        await queryRunner.query(`CREATE TYPE "public"."subscriptions_status_enum" AS ENUM('incomplete', 'trialing', 'active', 'past_due', 'canceled', 'unpaid', 'paused', 'incomplete_expired')`);
        await queryRunner.query(`CREATE TABLE "subscriptions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" integer NOT NULL, "customer_id" uuid NOT NULL, "plan_id" uuid, "price_id" uuid, "stripe_subscription_id" character varying(255) NOT NULL, "stripe_checkout_session_id" character varying(255), "status" "public"."subscriptions_status_enum" NOT NULL DEFAULT 'incomplete', "current_period_start" TIMESTAMP, "current_period_end" TIMESTAMP, "trial_end" TIMESTAMP, "cancel_at_period_end" boolean NOT NULL DEFAULT false, "canceled_at" TIMESTAMP, "metadata" jsonb NOT NULL DEFAULT '{}'::jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_a87248d73155605cf782be9ee5e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_59d692965cddf4c4efbf749f63" ON "subscriptions" ("stripe_checkout_session_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_3a2d09d943f39912a01831a927" ON "subscriptions" ("stripe_subscription_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_6ccf973355b70645eff37774de" ON "subscriptions" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_d0a95ef8a28188364c546eb65c" ON "subscriptions" ("user_id") `);
        await queryRunner.query(`CREATE TABLE "payments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" integer NOT NULL, "customer_id" uuid NOT NULL, "price_id" uuid, "stripe_checkout_session_id" character varying(255), "stripe_payment_intent_id" character varying(255), "amount" integer NOT NULL, "amount_refunded" integer NOT NULL DEFAULT '0', "currency" character varying(3) NOT NULL, "status" "public"."payments_status_enum" NOT NULL DEFAULT 'checkout_created', "description" text, "metadata" jsonb NOT NULL DEFAULT '{}'::jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_197ab7af18c93fbb0c9b28b4a59" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_94c6e6376625bc6710d7dbb4b6" ON "payments" ("stripe_payment_intent_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_7f0fb7e5b7e37b559fc8bb84f7" ON "payments" ("stripe_checkout_session_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_32b41cdb985a296213e9a928b5" ON "payments" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_427785468fb7d2733f59e7d7d3" ON "payments" ("user_id") `);
        await queryRunner.query(`CREATE TYPE "public"."subscription_events_previous_status_enum" AS ENUM('incomplete', 'trialing', 'active', 'past_due', 'canceled', 'unpaid', 'paused', 'incomplete_expired')`);
        await queryRunner.query(`CREATE TYPE "public"."subscription_events_new_status_enum" AS ENUM('incomplete', 'trialing', 'active', 'past_due', 'canceled', 'unpaid', 'paused', 'incomplete_expired')`);
        await queryRunner.query(`CREATE TABLE "subscription_events" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" integer NOT NULL, "subscription_id" uuid, "previous_status" "public"."subscription_events_previous_status_enum", "new_status" "public"."subscription_events_new_status_enum" NOT NULL, "plan_id" uuid, "price_id" uuid, "stripe_event_id" character varying(255), "reason" character varying(255), "metadata" jsonb NOT NULL DEFAULT '{}'::jsonb, "occurred_at" TIMESTAMP NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_2c4c43a54a31077d8a87b82c8b5" UNIQUE ("stripe_event_id"), CONSTRAINT "PK_7eb5647aa3071cffad0124bceee" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_485cf051a532ff3a47059d440d" ON "subscription_events" ("subscription_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_23441a9126495d13cb091efd52" ON "subscription_events" ("user_id", "occurred_at") `);
        await queryRunner.query(`CREATE TABLE "user_list_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "list_id" uuid NOT NULL, "user_id" integer NOT NULL, "media_type" "public"."user_list_items_media_type_enum" NOT NULL, "tmdb_id" integer NOT NULL, "title" character varying(500) NOT NULL, "poster_path" character varying(255), "release_date" date, "vote_average" numeric(4,1), "added_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_42e25b049faa18d32239ad58cff" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "ix_list_items_list_id" ON "user_list_items" ("list_id") `);
        await queryRunner.query(`CREATE INDEX "ix_list_recent" ON "user_list_items" ("list_id", "added_at", "id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_list_item" ON "user_list_items" ("list_id", "media_type", "tmdb_id") `);
        await queryRunner.query(`CREATE TABLE "user_lists" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" integer NOT NULL, "name" character varying(80) NOT NULL, "slug" character varying(100) NOT NULL, "list_key" character varying(40) NOT NULL, "is_system" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_5b95dd451cc96d45846e5e8db04" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "ix_user_lists_user_recent" ON "user_lists" ("user_id", "created_at") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_user_lists_user_slug" ON "user_lists" ("user_id", "slug") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_user_lists_user_key" ON "user_lists" ("user_id", "list_key") `);
        await queryRunner.query(`ALTER TABLE "customers" ADD CONSTRAINT "FK_11d81cd7be87b6f8865b0cf7661" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "prices" ADD CONSTRAINT "FK_91c9f1060b42b172d0883e13f44" FOREIGN KEY ("plan_id") REFERENCES "plans"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subscriptions" ADD CONSTRAINT "FK_98a4e1e3025f768de1493ecedec" FOREIGN KEY ("customer_id") REFERENCES "customers"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subscriptions" ADD CONSTRAINT "FK_e45fca5d912c3a2fab512ac25dc" FOREIGN KEY ("plan_id") REFERENCES "plans"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subscriptions" ADD CONSTRAINT "FK_7f7fe1f6132e48683387c32982c" FOREIGN KEY ("price_id") REFERENCES "prices"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_d0b02233df1c52323107fe7b4d7" FOREIGN KEY ("customer_id") REFERENCES "customers"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_d2dc25f4ccc2aca1a731a37046a" FOREIGN KEY ("price_id") REFERENCES "prices"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_list_items" ADD CONSTRAINT "FK_37562fdee30c6f6f17f956e273b" FOREIGN KEY ("list_id") REFERENCES "user_lists"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "user_list_items" DROP CONSTRAINT "FK_37562fdee30c6f6f17f956e273b"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_d2dc25f4ccc2aca1a731a37046a"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_d0b02233df1c52323107fe7b4d7"`);
        await queryRunner.query(`ALTER TABLE "subscriptions" DROP CONSTRAINT "FK_7f7fe1f6132e48683387c32982c"`);
        await queryRunner.query(`ALTER TABLE "subscriptions" DROP CONSTRAINT "FK_e45fca5d912c3a2fab512ac25dc"`);
        await queryRunner.query(`ALTER TABLE "subscriptions" DROP CONSTRAINT "FK_98a4e1e3025f768de1493ecedec"`);
        await queryRunner.query(`ALTER TABLE "prices" DROP CONSTRAINT "FK_91c9f1060b42b172d0883e13f44"`);
        await queryRunner.query(`ALTER TABLE "customers" DROP CONSTRAINT "FK_11d81cd7be87b6f8865b0cf7661"`);
        await queryRunner.query(`DROP INDEX "public"."uq_user_lists_user_key"`);
        await queryRunner.query(`DROP INDEX "public"."uq_user_lists_user_slug"`);
        await queryRunner.query(`DROP INDEX "public"."ix_user_lists_user_recent"`);
        await queryRunner.query(`DROP TABLE "user_lists"`);
        await queryRunner.query(`DROP INDEX "public"."uq_list_item"`);
        await queryRunner.query(`DROP INDEX "public"."ix_list_recent"`);
        await queryRunner.query(`DROP INDEX "public"."ix_list_items_list_id"`);
        await queryRunner.query(`DROP TABLE "user_list_items"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_23441a9126495d13cb091efd52"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_485cf051a532ff3a47059d440d"`);
        await queryRunner.query(`DROP TABLE "subscription_events"`);
        await queryRunner.query(`DROP TYPE "public"."subscription_events_new_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."subscription_events_previous_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_427785468fb7d2733f59e7d7d3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_32b41cdb985a296213e9a928b5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7f0fb7e5b7e37b559fc8bb84f7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_94c6e6376625bc6710d7dbb4b6"`);
        await queryRunner.query(`DROP TABLE "payments"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d0a95ef8a28188364c546eb65c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6ccf973355b70645eff37774de"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3a2d09d943f39912a01831a927"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_59d692965cddf4c4efbf749f63"`);
        await queryRunner.query(`DROP TABLE "subscriptions"`);
        await queryRunner.query(`DROP TYPE "public"."subscriptions_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f6fda7cdd493f9803d5173bb3e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_91c9f1060b42b172d0883e13f4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8f45cde063ad75609a556c071b"`);
        await queryRunner.query(`DROP TABLE "prices"`);
        await queryRunner.query(`DROP TYPE "public"."prices_interval_enum"`);
        await queryRunner.query(`DROP TYPE "public"."prices_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_95f7ef3fc4c31a3545b4d825dd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9f48ef3635529b001d3b06cce0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a82db0f05657dd1382a58bc9d9"`);
        await queryRunner.query(`DROP TABLE "plans"`);
        await queryRunner.query(`DROP TYPE "public"."plans_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_11d81cd7be87b6f8865b0cf766"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_be246a1643960ed2529d08b8b8"`);
        await queryRunner.query(`DROP TABLE "customers"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_64c90edc7310c6be7c10c96f67"`);
        await queryRunner.query(`DROP TABLE "notification_preferences"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9a8a82462cab47c73d25f49261"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f12148ce379462ebbb4d06cc13"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_aef1c7aef3725068e5540f8f00"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_77ee7b06d6f802000c0846f3a5"`);
        await queryRunner.query(`DROP TABLE "notifications"`);
        await queryRunner.query(`DROP INDEX "public"."idx_contact_messages_is_read"`);
        await queryRunner.query(`DROP INDEX "public"."idx_contact_messages_created_at"`);
        await queryRunner.query(`DROP TABLE "contact_messages"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e36371b9a0eaf48419f30da4a1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8eb1cabd6b6e30a13c1dc85326"`);
        await queryRunner.query(`DROP TABLE "black_list_tokens"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE IF EXISTS "public"."user_list_items_media_type_enum"`);
        await queryRunner.query(`DROP TYPE IF EXISTS "public"."notifications_type_enum"`);
        await queryRunner.query(`DROP TYPE IF EXISTS "public"."payments_status_enum"`);
        await queryRunner.query(`DROP TYPE IF EXISTS "public"."users_status_enum"`);
        await queryRunner.query(`DROP TYPE IF EXISTS "public"."users_role_enum"`);
    }

}
